### PR TITLE
Add option to restrict number of answers shown

### LINKED ISSUE #99: Is it possible to show only 5 random answers from 10 possible answers ?
Hi i'm a french med student and in my university we have a huge database of questions for our final exams. So basically I've just found your add-on on ANKIweb annd i added the posibility to have 10 answers, but for the exam of my university, we will have like 10 answers ( 5 goods and 5 wrongs  ) and the application will pick randomly 5 answers then show it to us.

Is it possible to add this kind of feature for your add on ? 

With your answer you will massively help a lot of people

Best regards

### PR DESCRIPTION
**Pull request by 3ter**
This PR should address the issues kindly requested in https://github.com/zjosua/anki-mc/pull/100#pullrequestreview-1264722077

Fixes #99 

PS It depends on #102

### CODE REVIEW

**Comment by zjosua** [comment]
Looks good so far.
For cases where only wrong answers are displayed, there should be a "Clear selection" button on the front when the QType is 2 (single choice).

**Comment by 3ter** [comment]
I rebased the branch onto `master` to make the diff more readable. I remember we had this issue some time ago in a previous PR when I didn't know what to do in the case you have a feature branch depending on another one that has been merged to master in the meantime.

The solution is `git rebase --onto master next topic` from https://git-scm.com/docs/git-rebase

**Comment by 3ter** [comment]
> Looks good so far. For cases where only wrong answers are displayed, there should be a "Clear selection" button on the front when the QType is 2 (single choice) and `maxQuestionsToShow` > 0.

I understand that this is a problem that needs adressing, otherwise you would be bound to answer incorrectly.

I think it would be more fitting to the nature of _single choice_ to always get the right answer in there with the shown questions. Let's see if I can come up with something.

**Comment by 3ter** [comment]
Now the preview is broken. Let me have a look again.

**Comment by 3ter** [comment]
There's still a bug with the solutions now 😆. Perhaps tomorrow then.

**Comment by 3ter** [comment]
@zjosua Now I consider it ready. I had time to test it with all card types with and without restricting the number of possible choices shown.

**Comment by zjosua** [comment]
Works fine for me too.

**Pull request merged**
