### PR TITLE
Fixed correct answer text. Introduced hint button. 

### PR DESCRIPTION
**Pull request by eyalk11**
Forgot to mention, moved sources to question...

The hint is useful for me in case of studying words. I first don't want to see list of answers, and if I kind of know the words, then I want to.. Ideally, it should be optional.

### CODE REVIEW

**Review by Schlauer-Hax — APPROVED** [review]
Looks like it would work! Do you mind adding the changed code in card/front.html and card/back.html?

**Comment by eyalk11** [comment]
Hi, I improved it more, added card front and back.

well I did something a bit controversial. I added FAKE options that are another possible questions. The idea is if type 2 is chosen, there will be two templates. The regular type is the same. The second one switches the roles of questions and answers,  and asks what question fits the right answer. I assumed (w.l.g) that the first question is always correct (that can be assumed in case of type 2 ).

**Comment by ksaadDE** [comment]
When will this be pushed into master?

**Comment by 3ter** [comment]
> Just a question. Why not reading the front and back from the html files?

#89

If you still want to make another stand for your changes after above mentioned PR has been merged you're welcome to do so. Otherwise I'm going to close it for now.

**Comment by 3ter** [comment]
Closing as inactive (parts of the PR have already been included into main).

**Pull request closed without merging**
